name: run_Python

on:
  workflow_dispatch
  

jobs:
  PYTHON:
    runs-on: ubuntu-latest


    steps:
      - name: python checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2

      - name: run
        run: python try1.py

      - name: secret
        env: 
          Secret: ${{secrets.key}}
        run: echo "my secret is $Secret"
      
  ALWAYs:
     runs-on: ubuntu-latest
     needs:
     if: ${{ always() }}
       
     steps:
      - name: print
        run: echo"this will always run"